baseURL: "https://example.com/"
languageCode: "en-gb"
title: "Hugo Theme - Prav"
theme: "hugo-theme-prav"

pygmentsCodeFences: true
pygmentsStyle: "perldoc"

# If you want to track using GA or use disqus for comments, uncomment the 
# following and add the correct values
#googleAnalytics: ""
#disqusShortname: ""

# The settings below are used throughout the theme.
# Please update!
params:
  title: "Hugo Theme - Prav"
  tagline: "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
  author: "Pravin Paratey"
  authorImgPath: "/img/author.png"
  authorBlurb: "Something about me"
  mainSections: ["posts", "post"]

# If you do not want a social icon, just comment it out
# Please update the example values!
social:
  email: "mailto:example@example.com"
  facebook: "https://www.facebook.com/example"
  twitter: "http://twitter.com/example"
  medium: "https://www.medium.com/@example"
  github: "https://github.com/example"
  linkedin: "http://uk.linkedin.com/in/example"
  mastodon: "https://mstdn.social/example"

# Set unsafe mode to allow markdownify to work with goldmark
# This is important. Please do not delete. It is used to re-render markdown
markup:
  goldmark:
    renderer:
      unsafe: true